services:
# Launch emulator and appium instance
  android-service:
    image: android-emulator
    build:
      context: .
      args:
        # x86
        ARCH: "x86"           # 默认x86架构，可通过build args覆盖
        API_LEVEL: "28"          # 默认API 28(Android 9)
        BUILD_TOOLS: "28.0.3"
        EMULATOR_DEVICE: "pixel_3a"
        EMULATOR_NAME: "pixel"
    ports:
      - 4725:4725
    container_name: android
    environment:
      - APPIUM_PORT=4725
      # 如需覆盖设备/架构/系统等参数，可在此添加环境变量
    privileged: true
    command:
      - bash
      - -c
      - | 
         ./start_emu_headless.sh
# Starting VNC server
  vnc-service:
    image: android-emulator
    build: .
    ports:
      - 5900:5900
      - 6080:6080
    # 5900: VNC server port
    # 6080: Web VNC port
    container_name: VNCService
    environment: 
      VNC_PASSWORD: 123
    privileged: true
    command:
      - bash
      - -c
      - |
        ./scripts/start_vnc.sh

  vnc7-service:
    image: android7-emulator
    build: .
    ports:
      - 5901:5900
      - 6081:6080
    container_name: VNCService7
    environment: 
      VNC_PASSWORD: 123
    privileged: true
    command:
      - bash
      - -c
      - |
        ./scripts/start_vnc.sh
