version: "4"
services:
# Launch emulator and appium instance
  android-service:
    image: android-emulator
    build:
      context: .
      args:
        # x86_64
        ARCH: "arm64-v8a"
        API_LEVEL: "28"
        BUILD_TOOLS: "28.0.3"
        EMULATOR_DEVICE: "pixel_3a"
        EMULATOR_NAME: "pixel"
    ports:
      - 4725:4725
    container_name: android
    environment:
      - APPIUM_PORT=4725
    privileged: true
    command:
      - bash
      - -c
      - | 
         ./start_emu_headless.sh
    tty: true
    stdin_open: true
# # Starting VNC server
#   VNC-Service:
#     image: android-emulator
#     build: .
#     ports:
#       - 5900:5900
#     container_name: VNC-Service
#     environment: 
#       VNC_PASSWORD: 123
#     privileged: true
#     command:
#       - bash
#       - -c
#       - |
#         $START_VNC
#     tty: true
#     stdin_open: true
