name: docker push

on:
  workflow_dispatch:
    inputs:
      Tag:
        description: 'Select docker tag to push'     
        required: true
        default: 'latest' 
        type: choice
        options:
        - latest
        - nexus6_playstore
        - pixelC_tablet_playstore
      Emulator:  
        description: 'Select Emulator Device'     
        required: false
        default: 'pixel_c' 
        type: choice
        options:
        - pixel_c
        - Nexus 6
      EmulatorName:  
        description: 'Select Emulator Name'     
        required: false
        default: 'pixel_c' 
        type: choice
        options:
        - pixel_c
        - nexus

jobs:
  Pushing-docker-image:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
      
    - name: Docker build image
      run: docker build --platform windows/amd64 --build-arg EMULATOR_DEVICE="${{ github.event.inputs.Emulator }}" --build-arg EMULATOR_NAME="${{ github.event.inputs.EmulatorName }}" -t amrka/android-emulator:${{ github.event.inputs.Tag }} .
      
    - name: Push docker image
      run:  docker push amrka/android-emulator:${{ github.event.inputs.Tag }}
