name: Build and Push Docker Image

on:
  push:
    branches:
      - main # 触发构建的分支

jobs:
  build:
    runs-on: ubuntu-latest # 选择运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: . # Dockerfile 所在目录
          push: true # 是否推送到 Docker Hub
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/roid-vnc:latest

      - name: Logout from Docker Hub
        uses: docker/logout-action@v1
